from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel
from fpdf import FPDF
from datetime import datetime
import os

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

REPORT_DIR = "reports"
os.makedirs(REPORT_DIR, exist_ok=True)

app.mount("/reports", StaticFiles(directory=REPORT_DIR), name="reports")

class ReportRequest(BaseModel):
    patient_name: str
    patient_id: str
    exercise: str
    exercise_key: str
    reps: int
    sets: int | None = None
    duration: float
    avg_speed: float
    form_score: float
    age: int | None = None
    medical_history: str | None = None
    goal: str | None = None

def make_pdf(req: ReportRequest) -> str:
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", "B", 16)
    pdf.cell(0, 10, "Physiotherapy Exercise Session Report – TherapEase", ln=True)

    pdf.set_font("Arial", "", 12)
    pdf.ln(4)
    pdf.multi_cell(0, 8, f"Patient Name: {req.patient_name}")
    pdf.multi_cell(0, 8, f"Patient ID: {req.patient_id}")
    pdf.multi_cell(0, 8, f"Age: {req.age}")
    pdf.multi_cell(0, 8, f"Date: {datetime.now().strftime('%d %B %Y')}")

    pdf.ln(5)
    pdf.set_font("Arial", "B", 13)
    pdf.multi_cell(0, 8, "Session Summary")

    pdf.set_font("Arial", "", 12)
    pdf.multi_cell(0, 7, f"Exercise: {req.exercise}")
    pdf.multi_cell(0, 7, f"Reps: {req.reps}")
    pdf.multi_cell(0, 7, f"Duration: {req.duration:.1f} sec")
    pdf.multi_cell(0, 7, f"Average Speed: {req.avg_speed:.2f}")
    pdf.multi_cell(0, 7, f"Form Score: {req.form_score * 100:.1f} / 100")

    filename = f"{req.exercise_key}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    filepath = os.path.join(REPORT_DIR, filename)
    pdf.output(filepath)
    return filepath

from fastapi import Request

@app.post("/generate_report")
async def generate_report(request: Request):
    """
    Simple PDF generator for a single exercise session.
    Uses only ASCII characters so FPDF (latin-1) doesn't crash.
    Frontend sends JSON; we return { "url": "/reports/filename.pdf" }.
    """
    data = await request.json()
    print("Incoming report data:", data)

    # read fields safely with defaults
    patient_name = data.get("patient_name", "Unknown Patient")
    patient_id = data.get("patient_id", "N/A")
    exercise = data.get("exercise", "Exercise")
    exercise_key = data.get("exercise_key", "squat")

    reps = int(data.get("reps", 0) or 0)
    sets = int(data.get("sets", 1) or 1)
    duration = float(data.get("duration", 0.0) or 0.0)
    avg_speed = float(data.get("avg_speed", 0.0) or 0.0)
    form_score = float(data.get("form_score", 0.0) or 0.0)

    date_str = datetime.now().strftime("%d %B %Y")

    # ------- create a simple, ASCII-only report -------
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # Title (NO en dash, only hyphen)
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, "TherapEase Exercise Session Report", ln=1, align="C")

    pdf.ln(4)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Patient Details", ln=1)

    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 6, f"Name: {patient_name}", ln=1)
    pdf.cell(0, 6, f"Patient ID: {patient_id}", ln=1)
    pdf.cell(0, 6, f"Date of Report: {date_str}", ln=1)

    pdf.ln(4)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Session Summary", ln=1)

    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 6, f"Exercise: {exercise} ({exercise_key})", ln=1)
    pdf.cell(0, 6, f"Sets: {sets}", ln=1)
    pdf.cell(0, 6, f"Total Reps: {reps}", ln=1)
    pdf.cell(0, 6, f"Duration: {duration:.1f} sec", ln=1)
    pdf.cell(0, 6, f"Average Speed: {avg_speed:.2f}", ln=1)
    pdf.cell(0, 6, f"Form Score: {form_score:.1f} / 100", ln=1)

    pdf.ln(6)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Therapist Remarks", ln=1)

    pdf.set_font("Helvetica", "", 11)
    remarks = (
        "Session auto-generated by TherapEase. "
        "Please review the metrics above and adjust the exercise "
        "prescription as needed."
    )
    pdf.multi_cell(0, 5, remarks)

    # ------- save PDF and respond with URL -------
    filename = f"report_{patient_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    filepath = os.path.join(REPORT_DIR, filename)
    pdf.output(filepath)

    print("Saved report to:", filepath)
    return {"url": f"/reports/{filename}"}


@app.get("/reports/{filename}")
def get_report(filename: str):
    filepath = os.path.join("reports", filename)
    return FileResponse(filepath, media_type="application/pdf")
